/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.ChuyenDeDAO;
import Utilities.Auths;
import Utilities.MsgBox;
import Utilities.Validate;
import Utilities.XImages;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Model.ChuyenDe;
import Model.NhanVien;

/**
 *
 * @author OS
 */
public class QL_ChuyenDe extends javax.swing.JFrame {

    /**
     * Creates new form QL_ChuyenDe
     */
    DefaultTableModel model;

    public QL_ChuyenDe() {
        initComponents();
        init();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblQLChuyenDe = new javax.swing.JLabel();
        tab = new javax.swing.JTabbedPane();
        pblCapNhat = new javax.swing.JPanel();
        lblHinhLogo = new javax.swing.JLabel();
        pnlAnh = new javax.swing.JPanel();
        lblAnh = new javax.swing.JLabel();
        lblMaChuyenDe = new javax.swing.JLabel();
        txtMaChuyenDe = new javax.swing.JTextField();
        lblTenChuyenDe = new javax.swing.JLabel();
        txtTenChuyenDe = new javax.swing.JTextField();
        lblThoiGian = new javax.swing.JLabel();
        txtThoiGian = new javax.swing.JTextField();
        lblHocPhi = new javax.swing.JLabel();
        txtHocPhi = new javax.swing.JTextField();
        lblMoTa = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaMoTa = new javax.swing.JTextArea();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        pnlDanhSach = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblChuyenDe = new rojeru_san.complementos.RSTableMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("EduSys - QUẢN LÝ CHUYÊN ĐỀ");

        lblQLChuyenDe.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblQLChuyenDe.setForeground(new java.awt.Color(0, 112, 192));
        lblQLChuyenDe.setText("QUẢN LÝ CHUYÊN ĐỀ");

        lblHinhLogo.setText("Hình Logo");

        pnlAnh.setBackground(new java.awt.Color(255, 255, 255));
        pnlAnh.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 142, 53), 3, true));

        lblAnh.setBackground(new java.awt.Color(255, 255, 255));
        lblAnh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAnh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAnhMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlAnhLayout = new javax.swing.GroupLayout(pnlAnh);
        pnlAnh.setLayout(pnlAnhLayout);
        pnlAnhLayout.setHorizontalGroup(
            pnlAnhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAnh, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
        );
        pnlAnhLayout.setVerticalGroup(
            pnlAnhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAnh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lblMaChuyenDe.setText("Mã chuyên đề");

        txtMaChuyenDe.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        lblTenChuyenDe.setText("Tên chuyên đề");

        txtTenChuyenDe.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        lblThoiGian.setText("Thời lượng(giờ)");

        txtThoiGian.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        lblHocPhi.setText("Học phí");

        txtHocPhi.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtHocPhi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHocPhiActionPerformed(evt);
            }
        });

        lblMoTa.setText("Mô tả chuyên đề");

        txaMoTa.setColumns(20);
        txaMoTa.setRows(5);
        jScrollPane1.setViewportView(txaMoTa);

        btnThem.setText("Thêm");
        btnThem.setMaximumSize(new java.awt.Dimension(65, 29));
        btnThem.setPreferredSize(new java.awt.Dimension(65, 29));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.setMaximumSize(new java.awt.Dimension(65, 29));
        btnSua.setPreferredSize(new java.awt.Dimension(65, 29));
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xoá");
        btnXoa.setMaximumSize(new java.awt.Dimension(65, 29));
        btnXoa.setPreferredSize(new java.awt.Dimension(65, 29));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnMoi.setText("Mới");
        btnMoi.setMaximumSize(new java.awt.Dimension(65, 29));
        btnMoi.setPreferredSize(new java.awt.Dimension(65, 29));
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        btnFirst.setText("<<");
        btnFirst.setMaximumSize(new java.awt.Dimension(65, 29));
        btnFirst.setPreferredSize(new java.awt.Dimension(65, 29));
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        btnBack.setText("|<");
        btnBack.setMaximumSize(new java.awt.Dimension(65, 29));
        btnBack.setPreferredSize(new java.awt.Dimension(65, 29));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnNext.setText(">|");
        btnNext.setMaximumSize(new java.awt.Dimension(65, 29));
        btnNext.setPreferredSize(new java.awt.Dimension(65, 29));
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnLast.setText(">>");
        btnLast.setMaximumSize(new java.awt.Dimension(65, 29));
        btnLast.setPreferredSize(new java.awt.Dimension(65, 29));
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pblCapNhatLayout = new javax.swing.GroupLayout(pblCapNhat);
        pblCapNhat.setLayout(pblCapNhatLayout);
        pblCapNhatLayout.setHorizontalGroup(
            pblCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pblCapNhatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pblCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pblCapNhatLayout.createSequentialGroup()
                        .addComponent(lblMoTa)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pblCapNhatLayout.createSequentialGroup()
                        .addGroup(pblCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pblCapNhatLayout.createSequentialGroup()
                                .addGroup(pblCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblHinhLogo)
                                    .addComponent(pnlAnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(pblCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMaChuyenDe)
                                    .addComponent(txtTenChuyenDe)
                                    .addComponent(txtThoiGian)
                                    .addGroup(pblCapNhatLayout.createSequentialGroup()
                                        .addGroup(pblCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblMaChuyenDe)
                                            .addComponent(lblTenChuyenDe)
                                            .addComponent(lblThoiGian)
                                            .addComponent(lblHocPhi))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtHocPhi))))
                        .addGap(24, 24, 24))
                    .addGroup(pblCapNhatLayout.createSequentialGroup()
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnFirst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 16, Short.MAX_VALUE))))
        );
        pblCapNhatLayout.setVerticalGroup(
            pblCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pblCapNhatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pblCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHinhLogo)
                    .addComponent(lblMaChuyenDe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pblCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pblCapNhatLayout.createSequentialGroup()
                        .addComponent(txtMaChuyenDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTenChuyenDe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTenChuyenDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblThoiGian)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblHocPhi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHocPhi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlAnh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMoTa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(pblCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFirst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tab.addTab("CẬP NHẬT", pblCapNhat);

        tblChuyenDe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "MÃ CHUYÊN ĐỀ", "TÊN CHUYÊN ĐỀ", "HỌC PHÍ", "THỜI LƯỢNG", "HÌNH"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblChuyenDe.setAltoHead(38);
        tblChuyenDe.setColorBackgoundHead(new java.awt.Color(153, 153, 192));
        tblChuyenDe.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tblChuyenDe.setColorSelBackgound(new java.awt.Color(255, 51, 51));
        tblChuyenDe.setFuenteHead(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        tblChuyenDe.setRowHeight(25);
        tblChuyenDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblChuyenDeMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblChuyenDe);
        if (tblChuyenDe.getColumnModel().getColumnCount() > 0) {
            tblChuyenDe.getColumnModel().getColumn(0).setMinWidth(130);
            tblChuyenDe.getColumnModel().getColumn(0).setPreferredWidth(130);
            tblChuyenDe.getColumnModel().getColumn(0).setMaxWidth(130);
            tblChuyenDe.getColumnModel().getColumn(1).setMinWidth(240);
            tblChuyenDe.getColumnModel().getColumn(1).setPreferredWidth(240);
            tblChuyenDe.getColumnModel().getColumn(1).setMaxWidth(240);
        }

        javax.swing.GroupLayout pnlDanhSachLayout = new javax.swing.GroupLayout(pnlDanhSach);
        pnlDanhSach.setLayout(pnlDanhSachLayout);
        pnlDanhSachLayout.setHorizontalGroup(
            pnlDanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
        );
        pnlDanhSachLayout.setVerticalGroup(
            pnlDanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDanhSachLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );

        tab.addTab("DANH SÁCH", pnlDanhSach);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tab)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblQLChuyenDe)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQLChuyenDe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tab, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHocPhiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHocPhiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHocPhiActionPerformed

    private void lblAnhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAnhMouseClicked
        chonAnh();
    }//GEN-LAST:event_lblAnhMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        this.insert();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        this.update();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        this.delete();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        this.clearForm();
    }//GEN-LAST:event_btnMoiActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        this.first();
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.previous();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        this.next();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
       this.last();
    }//GEN-LAST:event_btnLastActionPerformed

    private void tblChuyenDeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChuyenDeMouseClicked
        if(evt.getClickCount()==2){
            this.row = tblChuyenDe.getSelectedRow();
            this.edit();
        }
    }//GEN-LAST:event_tblChuyenDeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QL_ChuyenDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QL_ChuyenDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QL_ChuyenDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QL_ChuyenDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QL_ChuyenDe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAnh;
    private javax.swing.JLabel lblHinhLogo;
    private javax.swing.JLabel lblHocPhi;
    private javax.swing.JLabel lblMaChuyenDe;
    private javax.swing.JLabel lblMoTa;
    private javax.swing.JLabel lblQLChuyenDe;
    private javax.swing.JLabel lblTenChuyenDe;
    private javax.swing.JLabel lblThoiGian;
    private javax.swing.JPanel pblCapNhat;
    private javax.swing.JPanel pnlAnh;
    private javax.swing.JPanel pnlDanhSach;
    private javax.swing.JTabbedPane tab;
    private rojeru_san.complementos.RSTableMetro tblChuyenDe;
    private javax.swing.JTextArea txaMoTa;
    private javax.swing.JTextField txtHocPhi;
    private javax.swing.JTextField txtMaChuyenDe;
    private javax.swing.JTextField txtTenChuyenDe;
    private javax.swing.JTextField txtThoiGian;
    // End of variables declaration//GEN-END:variables

    ChuyenDeDAO dao = new ChuyenDeDAO();
    int row = -1;

    private void init() {
        this.setLocationRelativeTo(null);
        this.setIconImage(XImages.getAppIcon());
        this.filltable();
        this.row = -1;
        this.updatestatus();
    }

    private void filltable() {
        DefaultTableModel model = (DefaultTableModel) tblChuyenDe.getModel();
        model.setRowCount(0);
        try {
            List<ChuyenDe> list = dao.SelectAll();
            for (ChuyenDe cd : list) {
                model.addRow(new Object[]{
                    cd.getMaCD(), cd.getTenCD(), cd.getHocPhi(), cd.getThoiGian(), cd.getHinh()
                });
            }
            model.fireTableDataChanged();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void insert() {
        if (Validate.isEmpty(txtMaChuyenDe, "Mã Chuyên Đề đang rỗng!!") == false) {
            return;
        }
        if (Validate.isEmpty(txtTenChuyenDe, "Tên Chuyên Đề đang rỗng!!") == false) {
            return;
        }
        if (Validate.isEmpty(txtHocPhi, "Học Phí đang rỗng!!") == false) {
            return;
        }
        if (Validate.isEmpty(txtThoiGian, "Thời Lượng đang rỗng!!") == false) {
            return;
        }
        if (Validate.isEmptyTxa(txaMoTa, "Mô tả đang rỗng!!") == false) {
            return;
        }
        if (lblAnh.getToolTipText().equals("")) {
            JOptionPane.showMessageDialog(this, "Chuyên đề này cần ảnh nhận diện", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        ChuyenDe cd = getForm();
        try {
            dao.insert(cd);
            this.filltable();
            MsgBox.alert(this, "Thêm mới thành công");
            this.clearForm();
            
        } catch (Exception e) {
            MsgBox.alert(this, "Thêm mới thất bại");
        }
    }

    private void update() {
        if (Validate.isEmpty(txtMaChuyenDe, "Mã Chuyên Đề đang rỗng!!") == false) {
            return;
        }
        if (Validate.isEmpty(txtTenChuyenDe, "Tên Chuyên Đề đang rỗng!!") == false) {
            return;
        }
        if (Validate.isEmpty(txtHocPhi, "Học Phí đang rỗng!!") == false) {
            return;
        }
        if (Validate.isEmpty(txtThoiGian, "Thời Lượng đang rỗng!!") == false) {
            return;
        }
        if (Validate.isEmptyTxa(txaMoTa, "Mô tả đang rỗng!!") == false) {
            return;
        }
        if (lblAnh.getToolTipText().equals("")) {
            JOptionPane.showMessageDialog(this, "Chuyên đề này cần ảnh nhận diện", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        ChuyenDe cd = getForm();
        try {
            dao.update(cd);
            this.filltable();
            MsgBox.alert(this, "Update thành công");
            this.clearForm();
        } catch (Exception e) {
            MsgBox.alert(this, "Update không thành công");
        }
    }

    private void delete() {
        if (!Auths.isManager()) {
            MsgBox.alert(this, "Chỉ có Trưởng Phòng mới được xoá Chuyên Đề!!");
        } else {
            try {
                if (MsgBox.confirm(this, "Bạn có muốn xoá không?")) {
                    String MaCD = txtMaChuyenDe.getText();
                    dao.delete(MaCD);
                    this.filltable();
                    MsgBox.alert(this, "Xoá thành công");
                    this.clearForm();
                }
            } catch (Exception e) {
                MsgBox.alert(this, "Chuyên Đề này đã có khoá học!!");
            }
        }

    }

    private void clearForm() {
        ChuyenDe cd = new ChuyenDe();
        this.setForm(cd);
        this.row = -1;
        lblAnh.setIcon(null);
        this.updatestatus();
    }

    private void edit() {
        String MaCD = (String) tblChuyenDe.getValueAt(this.row, 0);
        //Lấy lên dữ liệu ChuyenDe theo MaChuyenDe vừa lấy
        ChuyenDe cd = dao.SelectById(MaCD);
        this.setForm(cd);
        tab.setSelectedIndex(0);
        this.updatestatus();
    }
    private void first(){
        this.row = 0;
        this.edit();
    }
    private void previous(){
        if(this.row >0){
            this.row--;
            this.edit();
        }
    }
    private void next(){
        if(this.row < tblChuyenDe.getRowCount()-1){
            this.row++;
            this.edit();
        }
    }
    private void last(){
        this.row = tblChuyenDe.getRowCount()-1;
        this.edit();
    }

    private void setForm(ChuyenDe cd) {
        txtMaChuyenDe.setText(cd.getMaCD());
        txtTenChuyenDe.setText(cd.getTenCD());
        txtThoiGian.setText(String.valueOf(cd.getThoiGian()));
        txtHocPhi.setText(String.valueOf(cd.getHocPhi()));
        txaMoTa.setText(cd.getMoTa());
        //Hiển thị hình và ghi tên hình vào tootip của label chứa hình
        if (cd.getHinh() != null) {
            lblAnh.setToolTipText(cd.getHinh());

            ImageIcon icon = XImages.read(cd.getHinh()); //Đọc lại File từ lớp tiện ích (logo)
            //Chuyển về ảnh và setSize bằng với lblAnh
            Image im = icon.getImage();
            Image image = im.getScaledInstance(lblAnh.getWidth(), lblAnh.getHeight(), im.SCALE_SMOOTH);

            //Chuyển về lại Icon và set vào cho lbl
            ImageIcon icon1 = new ImageIcon(image);
            lblAnh.setIcon(icon1);
        }
    }

    //Lấy dữ liệu từ forrm
    private ChuyenDe getForm() {
        ChuyenDe cd = new ChuyenDe();
        cd.setMaCD(txtMaChuyenDe.getText());
        cd.setTenCD(txtTenChuyenDe.getText());
        cd.setHocPhi((float) Double.parseDouble(txtHocPhi.getText()));
        cd.setThoiGian(Integer.parseInt(txtThoiGian.getText()));
        cd.setMoTa(txaMoTa.getText());
        cd.setHinh(lblAnh.getToolTipText()); //Lấy tên từ lbl chứa hình
        return cd;
    }

    private void chonAnh() {
        JFileChooser fileChooser = new JFileChooser("C:\\Users\\OS\\Desktop\\DuAnMau\\DuAnMau\\src\\DuAnMau_ImagesChuyenDe\\");
        int check = fileChooser.showOpenDialog(null);
        if (check == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile(); //Lấy ra tên File
            XImages.save(file); //Lưu file vào lớp tiện ích (logo)
            ImageIcon icon = XImages.read(file.getName()); //Đọc lại File từ lớp tiện ích (logo)
            //Chuyển về ảnh và setSize bằng với lblAnh
            Image im = icon.getImage();
            Image image = im.getScaledInstance(lblAnh.getWidth(), lblAnh.getHeight(), im.SCALE_SMOOTH);

            //Chuyển về lại Icon và set vào cho lbl
            ImageIcon icon1 = new ImageIcon(image);
            lblAnh.setIcon(icon1);
            lblAnh.setToolTipText(file.getName()); //Giữ lại tên File trong tooltip
        }
    }
    
    private void updatestatus(){
        boolean edit = (this.row >=0 ); //Trả về True nếu đang ở hàng lớn hơn 0
        boolean first = (this.row==0); //Trả về True nếu đang ở hàng đầu tiên
        boolean last = (this.row==tblChuyenDe.getRowCount()-1); //Trả về True nếu đang ở hàng cuối cùng
        
        //Trạng thái form
        txtMaChuyenDe.setEditable(!edit); //Không thể UPDATE  mã nhân viên 
        btnThem.setEnabled(!edit); //Không thể thêm khi đã có mã nhân viên
        btnMoi.setEnabled(edit);
        btnSua.setEnabled(edit); 
        btnXoa.setEnabled(edit);
        
        //Trạng thái điều hướng
        btnFirst.setEnabled(edit && !first); //Đang ở hàng ddaauf tiên thì không thể back
        btnBack.setEnabled(edit && !first);  
        btnNext.setEnabled(edit && !last);
        btnLast.setEnabled(edit && !last);  
    }

}
